"""CORRECTNESS of a CPU-tier MoE layer, against the float64 reference, on the REAL checkpoint.

This is the test the whole tier stands or falls on, and it is reachable with no GPU: the CPU tier's
input is safetensors bytes on disk and its output is a vector, so the entire numeric path can be
exercised on the host.

WHAT IT COMPARES
    `weights/cpu_worker.py`'s pure-numpy dequant-and-GEMM, driven through the real
    `CpuMoEWorker` submit/join handoff, against `tools/cpu_moe/fixture/L*/ref/y_f64.bin` — a
    float64 reference computed independently by `tools/cpu_moe/make_fixture.py` straight from the
    raw safetensors bytes, and the same reference the AVX-512 core was validated to rel_rms
    ~2e-07 against on 2026-09-04.

    So this is a THREE-way agreement: the C core, the stored reference, and the Python path the
    engine's seam actually calls. Two independent implementations of the checkpoint's NVFP4
    convention agreeing to 1e-14 is what makes the convention itself (see below) a finding rather
    than a guess.

THE FORMAT FINDING THIS TEST ENCODES
    `W = E2M1[code] * e4m3(weight_scale) * weight_scale_2`, with `weight_scale_2` a MULTIPLIER.
    `python/minisgl/quant/nvfp4.py` documents and implements llm-compressor's
    `weight_global_scale = 448*6/amax`, a DIVISOR, and keys on that NAME. This checkpoint spells it
    `weight_scale_2` and stores the RECIPROCAL. `test_the_documented_divisor_convention_is_absurd`
    is the regression: it asserts that using the documented sign produces |W| ~ 1e6, so a future
    change that "fixes" the sign to match the docstring fails loudly here instead of silently
    serving noise.

SKIPS, LOUDLY, if the fixture is absent — it is generated by
`tools/cpu_moe/make_fixture.py --out tools/cpu_moe/fixture/L0 --layer 0` against
/home/pat/.cache/hf-q4e and is ~35 KB per layer, so it is cheap to regenerate but is not checked
in as a binary blob.
"""

from __future__ import annotations

import json
import os

import pytest

np = pytest.importorskip("numpy")

from minisgl.weights.cpu_tier import HandoffError  # noqa: E402
from minisgl.weights.cpu_worker import (  # noqa: E402
    CpuMoEWorker,
    ExpertBlock,
    ReferenceBackend,
    dequant_nvfp4,
    e2m1_lut,
    e4m3_to_float,
    expert_mlp_f64,
)

_HERE = os.path.dirname(os.path.abspath(__file__))
_FIXTURE = os.path.normpath(os.path.join(_HERE, "..", "..", "tools", "cpu_moe", "fixture"))


def _layers_available():
    """Fixture layers whose CHECKPOINT SHARDS are also readable from this process.

    The shard paths are absolute and baked into `plan.txt`, so the fixture is usable on the bare
    host and NOT inside the serve container unless /home/pat/.cache/hf-q4e is mounted. Checking the
    shards here rather than letting the memmap fail turns "run this in the container" from 13 red
    tests into an honest skip with the mount in the reason.
    """
    if not os.path.isdir(_FIXTURE):
        return []
    out = []
    for d in sorted(os.listdir(_FIXTURE)):
        p = os.path.join(_FIXTURE, d)
        if not (
            os.path.isfile(os.path.join(p, "meta.json"))
            and os.path.isfile(os.path.join(p, "ref", "y_f64.bin"))
        ):
            continue
        try:
            with open(os.path.join(p, "meta.json")) as f:
                shards = json.load(f).get("shards") or []
        except Exception:
            continue
        if shards and all(os.path.isfile(s) for s in shards):
            out.append(d)
    return out


_LAYERS = _layers_available()
_needs_fixture = pytest.mark.skipif(
    not _LAYERS,
    reason=(
        "CPU-MoE fixture or its checkpoint shards are unreadable from this process. The "
        "shard paths in plan.txt are ABSOLUTE, so inside the serve container the checkpoint must "
        "be mounted at the same path (-v /home/pat/.cache/hf-q4e:/home/pat/.cache/hf-q4e:ro). "
        "Regenerate the fixture with e.g. "
        "`python3 tools/cpu_moe/make_fixture.py --model /home/pat/.cache/hf-q4e --layer 0 "
        "--out tools/cpu_moe/fixture/L0` (host-only, no GPU, ~35 KB)."
    ),
)


class _Fixture:
    """One layer's fixture: the byte plan, the stored route, x, and the float64 reference y."""

    def __init__(self, name: str) -> None:
        self.dir = os.path.join(_FIXTURE, name)
        with open(os.path.join(self.dir, "meta.json")) as f:
            self.meta = json.load(f)
        ref = os.path.join(self.dir, "ref")
        self.x = np.fromfile(os.path.join(ref, "x.bin"), dtype=np.float32)
        self.sel = np.fromfile(os.path.join(ref, "sel.bin"), dtype=np.int32)
        self.rw = np.fromfile(os.path.join(ref, "rw.bin"), dtype=np.float32)
        self.y = np.fromfile(os.path.join(ref, "y_f64.bin"), dtype=np.float64)
        self.plan = self._read_plan()
        self._mm: dict[int, np.ndarray] = {}

    def _read_plan(self):
        """`E <expert> <matrix> <shard> <code_off> <code_len> <scale_off> <scale_len> <N> <K> <g>`.

        matrix 0/1/2 = gate_proj / up_proj / down_proj, matching `make_fixture.PROJ`.
        """
        entries: dict[tuple[int, int], tuple] = {}
        self.shards: list[str] = []
        with open(os.path.join(self.dir, "plan.txt")) as f:
            for line in f:
                t = line.split()
                if not t:
                    continue
                if t[0] == "SHARDS":
                    continue
                if t[0] == "EXPERTS":
                    self.n_experts = int(t[1])
                    continue
                if t[0] == "E":
                    e, m, sh = int(t[1]), int(t[2]), int(t[3])
                    entries[(e, m)] = (
                        sh, int(t[4]), int(t[5]), int(t[6]), int(t[7]),
                        int(t[8]), int(t[9]), float(t[10]),
                    )
                elif t[0].startswith("/"):
                    self.shards.append(t[0])
        return entries

    def _shard(self, i: int):
        got = self._mm.get(i)
        if got is None:
            got = np.memmap(self.shards[i], dtype=np.uint8, mode="r")
            self._mm[i] = got
        return got

    def matrix(self, expert: int, m: int):
        sh, co, cl, so, sl, n, k, g = self.plan[(expert, m)]
        buf = self._shard(sh)
        codes = np.asarray(buf[co : co + cl])
        scales = np.asarray(buf[so : so + sl])
        assert cl == n * k // 2 and sl == n * k // 16, (cl, sl, n, k)
        return dequant_nvfp4(codes, scales, g, n, k), g

    def block(self, expert: int) -> ExpertBlock:
        gate, _ = self.matrix(expert, 0)
        up, _ = self.matrix(expert, 1)
        down, _ = self.matrix(expert, 2)
        return ExpertBlock(gate=gate, up=up, down=down)

    def sparse_backend(self) -> tuple[ReferenceBackend, list[int]]:
        """A backend holding ONLY the routed experts, renumbered — the EP-local convention.

        Building all 512 would be 40 GB of float64. The renumbering is exactly
        `ExpertStackTable.local_view`'s: global id -> position in this rank's shard.
        """
        uniq = sorted(set(int(i) for i in self.sel))
        blocks = [self.block(e) for e in uniq]
        remap = {e: j for j, e in enumerate(uniq)}
        return ReferenceBackend(blocks), [remap[int(e)] for e in self.sel]


def _rel_rms(got, ref):
    return float(np.sqrt(np.mean((got - ref) ** 2)) / np.sqrt(np.mean(ref**2)))


# ════════════════════════════════════════════════════════════════════════════════════════════════
class TestCodebooks:
    """The two lookup tables. One definition per process or the three implementations drift."""

    def test_e2m1_matches_the_OCP_codebook_and_tools_cpu_moe_wload_hpp(self):
        lut = e2m1_lut()
        assert list(lut[:8]) == [0.0, 0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 6.0]
        assert list(lut[8:]) == [-0.0, -0.5, -1.0, -1.5, -2.0, -3.0, -4.0, -6.0]

    def test_e4m3_table_saturates_at_448_which_is_the_finding_that_pins_the_convention(self):
        """Byte 126 == 448 == FP8_E4M3_MAX. `down_proj`'s largest block-scale byte is 126 for EVERY
        expert, and only `scale = block_amax / FP4_MAX / weight_scale_2` can produce that
        saturation — one of the four independent checks that pinned `weight_scale_2` as a
        MULTIPLIER rather than the divisor `quant/nvfp4.py` documents."""
        t = e4m3_to_float()
        assert t[126] == 448.0
        assert t[0] == 0.0
        assert t[127] == 0.0  # NaN slot, mapped to 0 exactly as tools/cpu_moe/wload.hpp does
        assert t[254] == -448.0

    def test_e4m3_subnormals(self):
        t = e4m3_to_float()
        assert t[1] == pytest.approx(2.0**-9)  # smallest positive subnormal
        assert t[8] == pytest.approx(2.0**-6)  # smallest normal


@_needs_fixture
class TestDequantAgainstTheCheckpoint:
    def test_dequantized_weights_have_a_plausible_rms(self):
        f = _Fixture(_LAYERS[0])
        gate, _ = f.matrix(int(f.sel[0]), 0)
        rms = float(np.sqrt(np.mean(gate**2)))
        assert 1e-3 < rms < 1e-1, f"|W| rms={rms} is not a weight matrix"

    def test_the_documented_divisor_convention_is_absurd(self):
        """REGRESSION for the format finding. `quant/nvfp4.py` documents `weight_global_scale` as a
        DIVISOR; this checkpoint's `weight_scale_2` is its RECIPROCAL. If someone "fixes" the sign
        to match the docstring, |W| jumps by ~8 orders of magnitude and this fails LOUDLY instead of
        the serve quietly emitting noise."""
        f = _Fixture(_LAYERS[0])
        e = int(f.sel[0])
        sh, co, cl, so, sl, n, k, g = f.plan[(e, 0)]
        buf = f._shard(sh)
        wrong = dequant_nvfp4(
            np.asarray(buf[co : co + cl]), np.asarray(buf[so : so + sl]), 1.0 / g, n, k
        )
        assert float(np.abs(wrong).max()) > 1e5

    def test_the_group_scale_really_is_group_16(self):
        """A group-32 misread would still produce finite, plausible numbers — and wrong ones."""
        f = _Fixture(_LAYERS[0])
        e = int(f.sel[0])
        sh, co, cl, so, sl, n, k, g = f.plan[(e, 2)]
        assert sl * 16 == n * k
        assert cl * 2 == n * k


@_needs_fixture
class TestFullLayerCorrectness:
    """The headline: a full CPU-tier layer (top-10, gate/up, SiLU-mul, down, routing weights)."""

    @pytest.mark.parametrize("layer", _LAYERS)
    def test_matches_the_float64_reference(self, layer):
        f = _Fixture(layer)
        backend, local_ids = f.sparse_backend()
        got = backend.compute(f.x.astype(np.float64), local_ids, f.rw.astype(np.float64))
        assert got.shape == f.y.shape
        rel = _rel_rms(got, f.y)
        # Both sides are float64 over the same bytes, so this is exact to double rounding — far
        # tighter than the C core's 2e-07, which is fp32 accumulation.
        assert rel < 1e-13, f"{layer}: rel_rms={rel:.3e}"
        assert float(np.sqrt(np.mean(f.y**2))) == pytest.approx(f.meta["ref_rms"], rel=1e-9)

    def test_the_routing_weights_are_load_bearing(self, ):
        """A layer that ignored `rw` would still produce a smooth, plausible vector."""
        f = _Fixture(_LAYERS[0])
        backend, local_ids = f.sparse_backend()
        unweighted = backend.compute(
            f.x.astype(np.float64), local_ids, np.ones(len(local_ids), dtype=np.float64)
        )
        assert _rel_rms(unweighted, f.y) > 0.5

    def test_dropping_one_expert_is_visible(self):
        """The failure mode a silent CPU tier produces: fluent output with an expert missing."""
        f = _Fixture(_LAYERS[0])
        backend, local_ids = f.sparse_backend()
        w = f.rw.astype(np.float64).copy()
        heaviest = int(np.argmax(w))
        w[heaviest] = 0.0
        dropped = backend.compute(f.x.astype(np.float64), local_ids, w)
        assert _rel_rms(dropped, f.y) > 0.05

    def test_summation_is_bit_reproducible_across_route_orderings_only_in_slot_order(self):
        """Slot-order summation is the contract (the native core is bit-identical at T=1/4/8).

        Permuting the route is NOT expected to be bit-identical — fp addition is not associative —
        and asserting that it is would be asserting something false. What IS asserted: the same
        route computed twice gives the same bits.
        """
        f = _Fixture(_LAYERS[0])
        backend, local_ids = f.sparse_backend()
        a = backend.compute(f.x.astype(np.float64), local_ids, f.rw.astype(np.float64))
        b = backend.compute(f.x.astype(np.float64), local_ids, f.rw.astype(np.float64))
        assert np.array_equal(a, b)

    def test_a_zero_weight_slot_contributes_exactly_nothing(self):
        """The MASK convention SPLIT mode and adaptive-K both rely on."""
        f = _Fixture(_LAYERS[0])
        backend, local_ids = f.sparse_backend()
        base = backend.compute(
            f.x.astype(np.float64), local_ids[:3], f.rw[:3].astype(np.float64)
        )
        padded = backend.compute(
            f.x.astype(np.float64),
            local_ids[:3] + [local_ids[0]],
            list(f.rw[:3].astype(np.float64)) + [0.0],
        )
        assert np.array_equal(base, padded)

    def test_an_out_of_range_expert_id_is_refused_not_silently_wrapped(self):
        f = _Fixture(_LAYERS[0])
        backend, local_ids = f.sparse_backend()
        with pytest.raises(Exception, match="out of range"):
            backend.compute(f.x.astype(np.float64), local_ids[:-1] + [9999], f.rw.astype(np.float64))


@_needs_fixture
class TestThroughTheAsyncSeam:
    """The same correctness, but driven through the real submit/join handoff the engine uses.

    A correctness proof of the kernel that bypasses the handoff proves nothing about the handoff —
    and the handoff is where the result can arrive attached to the wrong layer.
    """

    def test_a_layer_computed_via_submit_join_matches_the_reference(self):
        f = _Fixture(_LAYERS[0])
        backend, local_ids = f.sparse_backend()
        w = CpuMoEWorker(backend).start()
        try:
            w.begin_step(1)
            h = w.submit(0, f.x.astype(np.float64), local_ids, f.rw.astype(np.float64))
            got = w.join(h)
            w.barrier("end of step")
        finally:
            w.stop()
        assert _rel_rms(got, f.y) < 1e-13

    @pytest.mark.skipif(len(_LAYERS) < 2, reason="needs >= 2 fixture layers")
    def test_two_layers_in_one_step_keep_their_results_ATTACHED_to_the_right_layer(self):
        """The failure this exists for: layer L getting layer L+1's partial. Both are plausible."""
        fa, fb = _Fixture(_LAYERS[0]), _Fixture(_LAYERS[1])
        ba, ia = fa.sparse_backend()
        bb, ib = fb.sparse_backend()

        class _Router:
            name = "router"

            def compute(self, x, ids, weights):
                which, real_ids = ids
                return (ba if which == 0 else bb).compute(x, real_ids, weights)

        w = CpuMoEWorker(_Router()).start()
        try:
            w.begin_step(1)
            h0 = w.submit(0, fa.x.astype(np.float64), (0, ia), fa.rw.astype(np.float64))
            y0 = w.join(h0)
            h1 = w.submit(1, fb.x.astype(np.float64), (1, ib), fb.rw.astype(np.float64))
            y1 = w.join(h1)
            w.barrier("end of step")
        finally:
            w.stop()
        assert _rel_rms(y0, fa.y) < 1e-13
        assert _rel_rms(y1, fb.y) < 1e-13
        # ... and the two layers are genuinely different, so the test could have failed.
        assert _rel_rms(y0, fb.y) > 0.5


@_needs_fixture
class TestByteModelAgainstTheRealCheckpoint:
    """The capacity arithmetic, checked against the shard byte offsets rather than against itself."""

    def test_bytes_per_expert_are_what_the_plan_says_they_are(self):
        f = _Fixture(_LAYERS[0])
        e = int(f.sel[0])
        codes = sum(f.plan[(e, m)][2] for m in range(3))
        e4m3_scales = sum(f.plan[(e, m)][4] for m in range(3))
        assert codes == 2_457_600
        assert e4m3_scales == 307_200
        assert codes + e4m3_scales == f.meta["bytes_per_expert_e4m3"] == 2_764_800
        # The GPU path folds the same group scales to fp16 -> 2x the scale bytes.
        assert codes + 2 * e4m3_scales == 3_072_000
        assert (codes + e4m3_scales) / (codes + 2 * e4m3_scales) == 0.9

    def test_one_layer_token_of_top10_traffic(self):
        f = _Fixture(_LAYERS[0])
        assert f.meta["topk"] == 10
        assert 10 * f.meta["bytes_per_expert_e4m3"] == 27_648_000
