#!/usr/bin/env bash
# A/B the packed-dot2 Bf16GemvLoader e2e via its live consumer (the LM head).
#
# BASELINE = the image's BAKED fp8_wmma (b000dd0) -> the override file is moved ASIDE.
# Do NOT "baseline" by mounting another worktree's fp8_wmma unless that worktree has actually been
# BUILT: torch-ext/<pkg>/ ships __init__.py but _ops.py and the .so are generated by build_local.sh,
# so mounting an unbuilt tree shadows the good baked package with a broken one and the server dies
# with `ModuleNotFoundError: No module named 'fp8_wmma._ops'`.
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1
REPO="$PWD"; TOKS="${TOKS:-256}"; OUT="$REPO/tools/_dot2_ab_results.txt"
OVR="$REPO/docker-compose.override.yml"; STASH="$REPO/.override.stash.yml"
DOT2_PKG=/home/pat/code/rdna4-hip-kernels-mmax/fp8_wmma/torch-ext/fp8_wmma

[ -f "$DOT2_PKG/_ops.py" ] || { echo "FATAL: $DOT2_PKG is not built"; exit 1; }

wait_ready(){ for _ in $(seq 1 240); do curl -sf -m 2 http://127.0.0.1:1919/health >/dev/null 2>&1 && return 0; sleep 5; done; return 1; }
cleanup(){ docker compose -p lease-d2ab --profile serve down >/dev/null 2>&1 || true; }
trap cleanup EXIT INT TERM

run(){ local label="$1"
  echo "=== $label ===" | tee -a "$OUT"
  LEASE_NAME=d2ab MINISGL_IMAGE=minisgl-rdna4:lean FP8_WMMA_PKG="$DOT2_PKG" \
    gpu-lease -n 2 --detach --name d2ab -- docker compose -p lease-d2ab --profile serve up -d >/dev/null 2>&1
  if ! wait_ready; then echo "  BOOT FAILED:" | tee -a "$OUT"
    docker compose -p lease-d2ab --profile serve logs --tail 15 2>&1 | sed 's/^/    /' | tee -a "$OUT"
    cleanup; sleep 5; return 1; fi
  python3 "$REPO/tools/_hostloop_driver.py" "$TOKS" "$REPO/tools/_dot2_out_$label.txt" 2>&1 \
    | grep tok/s | sed 's/^/  /' | tee -a "$OUT"
  cleanup; sleep 5; }

: > "$OUT"
[ -f "$OVR" ] && mv "$OVR" "$STASH"          # baseline: baked fp8_wmma, no shadow mount
run baseline_baked
[ -f "$STASH" ] && mv "$STASH" "$OVR"        # dot2: shadow-mount the rebuilt package
run dot2
echo "=== done ===" | tee -a "$OUT"
